/*
   Copyright (c) 2019-2021 ZettaDB inc. All rights reserved.

   This source code is licensed under Apache 2.0 License,
   combined with Common Clause Condition 1.0, as detailed in the NOTICE file.
*/

#ifndef _NODE_MGR_TCP_ERROR_H_
#define _NODE_MGR_TCP_ERROR_H_

namespace kunlun_tcp
{

/* Error codes */
#define KL_TCP_ERR_SUCCESS				0
#define KL_TCP_ERR_INTERNAL_ERROR			-1
#define KL_TCP_ERR_ALLOC_FAIL			-2
#define KL_TCP_ERR_MESSAGE_INCOMPLETE		-3
#define KL_TCP_ERR_INVALID_FORMAT			-4
#define KL_TCP_ERR_BIGNUM_IS_NEGATIVE		-5
#define KL_TCP_ERR_STRING_TOO_LARGE		-6
#define KL_TCP_ERR_BIGNUM_TOO_LARGE		-7
#define KL_TCP_ERR_ECPOINT_TOO_LARGE		-8
#define KL_TCP_ERR_NO_BUFFER_SPACE			-9
#define KL_TCP_ERR_INVALID_ARGUMENT		-10
#define KL_TCP_ERR_KEY_BITS_MISMATCH		-11
#define KL_TCP_ERR_EC_CURVE_INVALID		-12
#define KL_TCP_ERR_KEY_TYPE_MISMATCH		-13
#define KL_TCP_ERR_KEY_TYPE_UNKNOWN		-14 /* XXX UNSUPPORTED? */
#define KL_TCP_ERR_EC_CURVE_MISMATCH		-15
#define KL_TCP_ERR_EXPECTED_CERT			-16
#define KL_TCP_ERR_KEY_LACKS_CERTBLOB		-17
#define KL_TCP_ERR_KEY_CERT_UNKNOWN_TYPE		-18
#define KL_TCP_ERR_KEY_CERT_INVALID_SIGN_KEY	-19
#define KL_TCP_ERR_KEY_INVALID_EC_VALUE		-20
#define KL_TCP_ERR_SIGNATURE_INVALID		-21
#define KL_TCP_ERR_LIBCRYPTO_ERROR			-22
#define KL_TCP_ERR_UNEXPECTED_TRAILING_DATA	-23
#define KL_TCP_ERR_SYSTEM_ERROR			-24
#define KL_TCP_ERR_KEY_CERT_INVALID		-25
#define KL_TCP_ERR_AGENT_COMMUNICATION		-26
#define KL_TCP_ERR_AGENT_FAILURE			-27
#define KL_TCP_ERR_DH_GEX_OUT_OF_RANGE		-28
#define KL_TCP_ERR_DISCONNECTED			-29
#define KL_TCP_ERR_MAC_INVALID			-30
#define KL_TCP_ERR_NO_CIPHER_ALG_MATCH		-31
#define KL_TCP_ERR_NO_MAC_ALG_MATCH		-32
#define KL_TCP_ERR_NO_COMPRESS_ALG_MATCH		-33
#define KL_TCP_ERR_NO_KEX_ALG_MATCH		-34
#define KL_TCP_ERR_NO_HOSTKEY_ALG_MATCH		-35
#define KL_TCP_ERR_NO_HOSTKEY_LOADED		-36
#define KL_TCP_ERR_PROTOCOL_MISMATCH		-37
#define KL_TCP_ERR_NO_PROTOCOL_VERSION		-38
#define KL_TCP_ERR_NEED_REKEY			-39
#define KL_TCP_ERR_PASSPHRASE_TOO_SHORT		-40
#define KL_TCP_ERR_FILE_CHANGED			-41
#define KL_TCP_ERR_KEY_UNKNOWN_CIPHER		-42
#define KL_TCP_ERR_KEY_WRONG_PASSPHRASE		-43
#define KL_TCP_ERR_KEY_BAD_PERMISSIONS		-44
#define KL_TCP_ERR_KEY_CERT_MISMATCH		-45
#define KL_TCP_ERR_KEY_NOT_FOUND			-46
#define KL_TCP_ERR_AGENT_NOT_PRESENT		-47
#define KL_TCP_ERR_AGENT_NO_IDENTITIES		-48
#define KL_TCP_ERR_BUFFER_READ_ONLY		-49
#define KL_TCP_ERR_KRL_BAD_MAGIC			-50
#define KL_TCP_ERR_KEY_REVOKED			-51
#define KL_TCP_ERR_CONN_CLOSED			-52
#define KL_TCP_ERR_CONN_TIMEOUT			-53
#define KL_TCP_ERR_CONN_CORRUPT			-54
#define KL_TCP_ERR_PROTOCOL_ERROR			-55
#define KL_TCP_ERR_FILE_EXIST			-56
#define KL_TCP_ERR_FILE_CREATE_FAILED	-57
#define KL_TCP_ERR_FILE_OPEN_FAILED  -58
#define KL_TCP_ERR_GET_FILENAME_FAILED  -59
#define KL_TCP_ERR_GET_FILESTAT_FAILED  -60
#define KL_TCP_ERR_DIRECTORY_FAILED  -61
#define KL_TCP_ERR_FILE_READ_FAILED  -62
#define KL_TCP_ERR_FILE_WRITE_FAILED  -63
#define KL_TCP_ERR_FILE_POSE_FAILED  -64
#define KL_TCP_ERR_WRITE_XML_FAILED  -65
#define KL_TCP_ERR_CHECKSUM_FAILED  -66
#define KL_TCP_ERR_SOCKET_READ_TIMEOUT  -67
#define KL_TCP_ERR_PTHREAD_CHILD_QUIT  -68
#define KL_TCP_ERR_FILE_READ_END  -69
#define KL_TCP_ERR_FILE_DIRECTOR_FAILED -70
#define KL_TCP_ERR_USER_NOT_FOUND			-71
#define KL_TCP_ERR_NOT_ROOT_GET_KEY_FAILED  -72

/* Translate a numeric error code to a human-readable error string */
const char *kl_tcp_err(int n);

}
#endif